### ISSUE TITLE
On-premise K8S cluster integrated with Sagmaker operator

### ISSUE THREAD

**Issue by tianyuan848192** [aws/amazon-sagemaker-operator-for-k8s#121]
**What would you like to be added**:
The solution might be work fine with EKS, but when i want to copy this solution to on premise data center K8S cluster, and i want give authorization by using IAM user's AK/SK. and i am not sure it will works and how it can be worked. 
**Why is this needed**:
Many of our cluster are build in on premise data center, and our way to manager credential is using AK/SK. Not sure if it will be acceptable.

**Comment by RedbackThomson** [comment]
Thanks for reaching out @tianyuan848192 

Currently we only officially support authentication using OIDC (supported natively by EKS). This method ensures credentials are short-lived and relies on roles rather than users. However, the manager pod uses any authentication method supported by the [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2) library. Therefore you should be able to pass environment variables or add pod annotations for other authentication libraries if you need to support those use cases.

**Comment by tianyuan848192** [comment]
Thanks, I have just test for using AK/SK, and it is works. Currently, i was trying to move this solution to AWS China Region, and i'v found the image 957583890962.dkr.ecr.us-east-1.amazonaws.com/amazon-sagemaker-operator-for-k8s could not be used in China Region, i was trying to copy the image to my ECR, and change the image in install.yaml. however, i found it still not work. do you know what we need changed if we want to migrate to China Region?

**Comment by wttat** [comment]
> **What would you like to be added**:
> The solution might be work fine with EKS, but when i want to copy this solution to on premise data center K8S cluster, and i want give authorization by using IAM user's AK/SK. and i am not sure it will works and how it can be worked.
> **Why is this needed**:
> Many of our cluster are build in on premise data center, and our way to manager credential is using AK/SK. Not sure if it will be acceptable.

hi tianyuan, I try to do the same work as yours too, I could run it on a k8s on ec2 but now facing some issues on-premise k8s, have you did it out?
