### ISSUE TITLE
Error Building SageMaker Types due to missing types in common/manual_deepcopy

### ISSUE THREAD

**Issue by Nagarajj** [aws/amazon-sagemaker-operator-for-k8s#122]
**What happened**:
Error Building SageMaker Types due to missing types in common/manual_deepcopy
(base) afccd2:example nj$ make all
go: creating new go.mod: module tmp
go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.2.5
/devel/projects/go_tutorial/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
controllers/guestbook_controller.go
go vet ./...
github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/common
../../../go_tutorial/pkg/mod/github.com/aws/amazon-sagemaker-operator-for-**k8s@v1.1.0/api/v1/common/manual_deepcopy.go:28:19: tag.DeepCopy undefined (type Tag has no field or method DeepCopy)
make: *** [vet] Error 2**

**What you expected to happen**:
Packaged types refer to types in zz_generated_deepcopy which are missing

**How to reproduce it (as minimally and precisely as possible)**:

Import of sagemaker types in Go Client fails build

import (
	trainingjobv1 "github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/trainingjob"
)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Operator version (controller image tag): v1.1.0
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Installation method:
- Others:

**Comment by RedbackThomson** [comment]
I believe this may be caused due to the generated deepcopy code not being checked in to the v1.1.0 branch. I attempted to backport this code previously but I don't think the go modules ever picked this up for some reason. I might suggest attempting this pinning to the `master` branch rather than `v1.1.0`. The APIs are backwardly compatible (while `master` is still pointed at a `v1.X`).
