### ISSUE TITLE
Submitted TrainingJob won't invoke SageMaker

### ISSUE THREAD

**Issue by angadkalra** [aws/amazon-sagemaker-operator-for-k8s#196]
I added a comment at the bottom to this previous closed issue: [https://github.com/aws/amazon-sagemaker-operator-for-k8s/issues/99]

Could we please reopen the issue?

**Comment by surajkota** [comment]
Hi @angadkalra, thanks for reporting the issue. Lets use this issue to communicate since your issue does not seem to be related to #99. Few questions:
- Did you install the operator namespace scoped? 
  - I think you did based on the args `      --namespace=sagemaker-jobs` I see in https://github.com/aws/amazon-sagemaker-operator-for-k8s/issues/99#issuecomment-1167607251 
  - Since you installed it namespace scoped, the controller only monitors and reconciles resources if the resources are created within that namespace.  Can you please try creating the training job in `sagemaker-jobs` namespace instead of `default`?
- Are you starting a new project or are you an existing user of this controller?
  - The reason I ask this is because if this is a new project, I highly recommend using ACK framework based [sagemaker-controller](https://github.com/aws-controllers-k8s/sagemaker-controller) which has the latest features and is the new version of this operator. Here is a tutorial to get started: https://aws-controllers-k8s.github.io/community/docs/tutorials/sagemaker-example/

**Comment by angadkalra** [comment]
@surajkota Thanks for responding!

Submitting job in sagemaker-jobs namespace works!

New project! I will checkout the ACK framework, thanks!

**Comment by surajkota** [comment]
Great!
