### ISSUE TITLE
README.md broken link

### ISSUE THREAD

**Issue by dferguson992** [aws/amazon-sagemaker-operator-for-k8s#197]
The "[install the operators](https://docs.aws.amazon.com/sagemaker/latest/dg/amazon-sagemaker-operators-for-kubernetes.html)" phrase in the README.me file points to the What is SageMaker page, it's been redirected to an unhelpful link.

**Comment by surajkota** [comment]
Hi @dferguson992, thanks for reporting the issue. Looks like this PR: https://github.com/awsdocs/amazon-sagemaker-developer-guide/pull/189 changed the name of pages leading to broken links. Please refer to this AWS docs page while we work on fixing it: https://docs.aws.amazon.com/sagemaker/latest/dg/kubernetes-sagemaker-operators.html.


On a side note, are you starting a new project or are you an existing user of this controller?
The reason I ask this is because if this is a new project, I highly recommend using ACK framework based [sagemaker-controller](https://github.com/aws-controllers-k8s/sagemaker-controller) which has the latest features and is the new version of this operator. Here is a tutorial to get started: https://aws-controllers-k8s.github.io/community/docs/tutorials/sagemaker-example/
